sudo: false
language: ruby
rvm:
- 2.1
script: gem install jekyll && jekyll build #&& gem install html-proofer && htmlproof ./_site

branches:
  only:
  - gh-pages
  - /pages-(.*)/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
